datasets:
  train:
  - name: Train
    metadata_path: /workspace/datasets/BRSPEECH/sets/train.csv
    base_dir: /workspace/datasets/BRSPEECH
    filename_column: filepath
    target_column: mos
  val:
  - name: Validation
    metadata_path: /workspace/datasets/BRSPEECH/sets/val.csv
    base_dir: /workspace/datasets/BRSPEECH
    filename_column: filepath
    target_column: mos
  test:
  - name: Test
    metadata_path: /workspace/datasets/BRSPEECH/sets/test.csv
    base_dir: /workspace/datasets/BRSPEECH
    filename_column: filepath
    target_column: mos
data:
  use_seqaug: false
  num_classes: 1
  target_sr: 16000
  mixup_alpha: 0.0
  use_rand_truncation: false
  min_duration: 2.0
  min_white_noise_amp: 0.01
  max_white_noise_amp: 0.1
  insert_white_noise: false
train:
  batch_size: 16
  shuffle: true
  num_workers: 12
wandb_entity: snaxofc10-utfpr-medianeira
title: CAL-MOS-facebook/wav2vec2-xls-r-300m-(epochs-100)-(bs-16)-(LR-0.001)-(WD-1e-06)-brspeech--(run-01)
model:
  model_type: dynamic
  model_name: facebook/wav2vec2-xls-r-300m
  mlp_input_dim: 1024
  mlp_hidden_dim: 1024
  mlp_num_layers: 1
  mlp_output_size: 1
  mlp_dropout: 0.1
  mlp_activation_func: relu
  layer_weight_strategy: per_layer
  num_feature_layers: -1
  specific_layer_idx: -1
  pooling_strategy: mean
  freeze_backbone: true
  transformer_hidden_size: 1024
  transformer_nhead: 4
  transformer_dim_feedforward: 2048
  transformer_activation: gelu
  transformer_dropout: 0.1
  transformer_layer_norm_eps: 1.0e-05
  transformer_bias: true
  transformer_num_hidden_layers: 2
optimizer:
  name: adamw
  params:
    min_learning_rate: 1.0e-06
    learning_rate: 0.001
    eps: 1.0e-08
    weight_decay: 1.0e-06
    betas:
    - 0.9
    - 0.98
scheduler:
  name: CosineWarmupLR
  params:
    warmup_lr: 1.0e-06
    warmup_steps: 500
tags:
- 16-BS
- LR-0.001
- WD-1e-06
- facebook/wav2vec2-xls-r-300m-HS
- 1024-AH
- 1024-HL
- 1-IS
trainer:
  accelerator: gpu
  max_epochs: 100
  num_sanity_val_steps: 2
  overfit_batches: 0.0
  log_every_n_steps: 10
  gradient_clip_val: 10.0
  gradient_clip_algorithm: norm
  val_check_interval: 1.0
  accumulate_grad_batches: 16
model_checkpoint:
  mode: max
  save_last: true
  save_weights_only: true
  monitor: val/spearman
  dirpath: ../checkpoints/mos-prediction
  filename: '{epoch:02d}-{step:02d}-{val/spearman:.4f}'
early_stopping:
  monitor: val/spearman
  patience: 20
  mode: max
  min_delta: 0.001
  verbose: true
dataset_name: brspeech
