datasets:
    name: "BVCC"
    train:
        - name: Train
          metadata_path: "/hadatasets/alef.ferreira/MOS-Prediction/DATASETS/BVCC/bvcc_train.csv"
          base_dir: "/hadatasets/alef.ferreira/MOS-Prediction/DATASETS/BVCC/main/DATA/wav"
          target_dir: "/hadatasets/alef.ferreira/MOS-Prediction/DATASETS/embeddings/BVCC/${model.normalized_model_name}/wav"
          filename_column: "wav_path"
          target_column: "avg_score"

    val:
        - name: Validation
          metadata_path: "/hadatasets/alef.ferreira/MOS-Prediction/DATASETS/BVCC/bvcc_dev.csv"
          base_dir: "/hadatasets/alef.ferreira/MOS-Prediction/DATASETS/BVCC/main/DATA/wav"
          target_dir: "/hadatasets/alef.ferreira/MOS-Prediction/DATASETS/embeddings/BVCC/${model.normalized_model_name}/wav"
          filename_column: "wav_path"
          target_column: "avg_score"

    test:
        - name: Test
          metadata_path: "/hadatasets/alef.ferreira/MOS-Prediction/DATASETS/BVCC/bvcc_test.csv"
          base_dir: "/hadatasets/alef.ferreira/MOS-Prediction/DATASETS/BVCC/main/DATA/wav"
          target_dir: "/hadatasets/alef.ferreira/MOS-Prediction/DATASETS/embeddings/BVCC/${model.normalized_model_name}/wav"
          filename_column: "wav_path"
          target_column: "avg_score"