datasets:
    name: "TMHINT-QI"
    train:
        - name: Train
          metadata_path: "/hadatasets/alef.ferreira/MOS-Prediction/DATASETS/tmhint-qi/tmhintqi_train.csv"
          base_dir: "/hadatasets/alef.ferreira/MOS-Prediction/DATASETS/tmhint-qi"
          target_dir: "/hadatasets/alef.ferreira/MOS-Prediction/DATASETS/embeddings/tmhint-qi/${model.normalized_model_name}"
          filename_column: "wav_path"
          target_column: "avg_score"

    val:
        - name: Validation
          metadata_path: "/hadatasets/alef.ferreira/MOS-Prediction/DATASETS/tmhint-qi/tmhintqi_dev.csv"
          base_dir: "/hadatasets/alef.ferreira/MOS-Prediction/DATASETS/tmhint-qi"
          target_dir: "/hadatasets/alef.ferreira/MOS-Prediction/DATASETS/embeddings/tmhint-qi/${model.normalized_model_name}"
          filename_column: "wav_path"
          target_column: "avg_score"

    test:
        - name: Test
          metadata_path: "/hadatasets/alef.ferreira/MOS-Prediction/DATASETS/tmhint-qi/tmhintqi_test.csv"
          base_dir: "/hadatasets/alef.ferreira/MOS-Prediction/DATASETS/tmhint-qi"
          target_dir: "/hadatasets/alef.ferreira/MOS-Prediction/DATASETS/embeddings/tmhint-qi/${model.normalized_model_name}"
          filename_column: "wav_path"
          target_column: "avg_score"