model:
    model_type: "dynamic"

    model_name: "facebook/mms-1b"

    mlp_input_dim: 1280 # Must be adapted to the model
    mlp_hidden_dim: ${model.mlp_input_dim} # Must be adapted to the model, should be the same as mlp_input_dim
    mlp_num_layers: 1
    mlp_output_size: ${data.num_classes}
    mlp_dropout: 0.1
    mlp_activation_func: "relu"
    layer_weight_strategy: "layer_adapter"
    adapter_dim: 1024
    num_feature_layers: 49 # Must be adapted to the model
    specific_layer_idx: -1 # Take the last layer
    pooling_strategy: "mean" # Take the mean of the sequence in the last layer

    freeze_backbone: true # Freeze the backbone model