model:
    model_type: "dynamic"

    model_name: "facebook/wav2vec2-large"

    mlp_input_dim: 2048 # Must be adapted to the model
    mlp_hidden_dim: ${model.mlp_input_dim} # Must be adapted to the model, should be the same as mlp_input_dim
    mlp_num_layers: 1
    mlp_output_size: ${data.num_classes}
    mlp_dropout: 0.1
    mlp_activation_func: "relu"
    layer_weight_strategy: "weighted_sum"
    num_feature_layers: 25 # Must be adapted to the model
    specific_layer_idx: -1 # Take the last layer
    pooling_strategy: "attpool" # Take the mean of the sequence in the last layer

    freeze_backbone: true # Freeze the backbone model